backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow
media_folder: "src/assets/img"

collections:
  - name: "catalogs"
    label: "სერვისების კატალოგი"
    folder: "src/catalogs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "კატალოგის ID (ლათინურად, ტირეებით)", name: "slug", widget: "string", hint: "მაგ: help-desk, it-support." }
      - { label: "კატეგორიის სათაური", name: "title", widget: "string" }
      - { label: "რიგითობა", name: "sort_order", widget: "number", default: 0 }
      - { label: "იკონი (Lucide)", name: "icon", widget: "string", required: false }
      - label: "სერვისების სია (მოკლე აღწერა)"
        name: "services"
        widget: "list"
        summary: "{{fields.name}}"
        fields:
          - { label: "სერვისის დასახელება", name: "name", widget: "string" }
          - { label: "იკონი (Lucide)", name: "icon", widget: "string", required: false }

  - name: "details"
    label: "სერვისების სრული აღწერა"
    folder: "src/details"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "აირჩიეთ კატალოგი"
        name: "catalog"
        widget: "relation"
        collection: "catalogs"
        search_fields: ["title"]
        value_field: "slug"
        display_fields: ["title"]
      - label: "დეტალური აღწერა"
        name: "body"
        widget: "markdown"
        hint: "სასურველი დიზაინისთვის, გამოიყენეთ ბულეტები. ყოველი პუნქტი დაიწყეთ `-` სიმბოლოთი."
      - { label: "Tags", name: "tags", widget: "hidden", default: "details" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "service-detail.njk" }
      - { label: "Permalink", name: "permalink", widget: "hidden", default: "/services/{{fields.catalog}}/" }
      
  - name: "pages"
    label: "მთავარი გვერდები"
    # ... (ეს სექცია უცვლელია, დატოვეთ როგორც არის) ...
  - name: "settings"
    label: "ზოგადი პარამეტრები"
    # ... (ეს სექცია უცვლელია, დატოვეთ როგორც არის) ...