backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow
media_folder: "src/assets/img"
public_folder: "/assets/img"

collections:
  - name: "managed_services_ka"
    label: "IT აუთსორსინგი (სერვისები)"
    folder: "src/services/ka"
    create: true
    slug: "{{slug}}"
    identifier_field: "slug"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "service-detail.njk" }
      - { label: "ენა", name: "lang", widget: "hidden", default: "ka" }
      - { label: "Permalink", name: "permalink", widget: "hidden", default: "/services/{{slug}}/" }
      - { label: "ფაილის სახელი (slug)", name: "slug", widget: "string", pattern: ['^[a-z0-9]+(?:-[a-z0-9]+)*$', "გამოიყენეთ მხოლოდ ლათინური ასოები, ციფრები და ტირე"] }
      - { label: "სერვისის სათაური", name: "title", widget: "string" }
      - { label: "რიგითობა", name: "sort_order", widget: "number", default: 0 }
      - { label: "მთავარი იკონი (Lucide-ის სახელი)", name: "icon", widget: "string", hint: "შედით lucide.dev/icons, იპოვეთ იკონი და ჩაწერეთ მისი სახელი, მაგ: server" }
      - { label: "ზოგადი მიმოხილვა", name: "general_description", widget: "markdown" }
      - label: "დეტალური მახასიათებლები (ბარათები)"
        name: "detailed_list"
        widget: "list"
        summary: "{{fields.point}}"
        fields:
          - { label: "ბარათის ტექსტი", name: "point", widget: "string" }
          - { label: "იკონი (Lucide-ის სახელი)", name: "icon", widget: "string", required: false, hint: "მაგ: shield, database, cloud" }

  - name: "managed_services_en"
    label: "IT Outsourcing (Services)"
    folder: "src/services/en"
    create: true
    slug: "{{slug}}"
    identifier_field: "slug"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "service-detail.njk" }
      - { label: "Language", name: "lang", widget: "hidden", default: "en" }
      - { label: "Permalink", name: "permalink", widget: "hidden", default: "/en/services/{{slug}}/" }
      - { label: "Filename (slug)", name: "slug", widget: "string", pattern: ['^[a-z0-9]+(?:-[a-z0-9]+)*$', "Use only latin letters, numbers, and dashes"] }
      - { label: "Service Title", name: "title", widget: "string" }
      - { label: "Sort Order", name: "sort_order", widget: "number", default: 0 }
      - { label: "Main Icon (Lucide Name)", name: "icon", widget: "string", hint: "Go to lucide.dev/icons, find an icon and type its name, e.g. server" }
      - { label: "General Description", name: "general_description", widget: "markdown" }
      - label: "Detailed Features (Cards)"
        name: "detailed_list"
        widget: "list"
        summary: "{{fields.point}}"
        fields:
          - { label: "Card Text", name: "point", widget: "string" }
          - { label: "Icon (Lucide Name)", name: "icon", widget: "string", required: false, hint: "e.g. shield, database, cloud" }
          
  - name: "pages_ka"
    label: "გვერდების მართვა (ქართული)"
    files:
      - { file: "src/ka/index.md", label: "მთავარი გვერდი", name: "index_ka", fields: [{ label: "სათაური", name: "title", widget: "string" }, { label: "Hero-ს სათაური", name: "hero_title", widget: "string" }, { label: "Hero-ს ქვესათაური", name: "hero_subtitle", widget: "text" }] }
      - { file: "src/ka/services.md", label: "სერვისების ჰაბი (2 ბარათი)", name: "services_page_ka", fields: [{ label: "სათაური (H1)", name: "title", widget: "string" }, { label: "ქვესათაური", name: "subtitle", widget: "text" }, { label: "ბარათი 1: სათაური", name: "card1_title", widget: "string" }, { label: "ბარათი 1: აღწერა", name: "card1_desc", widget: "text" }, { label: "ბარათი 1: პუნქტების სია", name: "card1_list", widget: "list", summary: "{{fields.item}}", fields: [{ label: "პუნქტი", name: "item", widget: "string" }] }, { label: "ბარათი 2: სათაური", name: "card2_title", widget: "string" }, { label: "ბარათი 2: აღწერა", name: "card2_desc", widget: "text" }, { label: "ბარათი 2: პუნქტების სია", name: "card2_list", widget: "list", summary: "{{fields.item}}", fields: [{ label: "პუნქტი", name: "item", widget: "string" }] }] }
      - { file: "src/ka/projects.md", label: "პროექტების გვერდი", name: "projects_page_ka", fields: [{ label: "სათაური (H1)", name: "title", widget: "string" }, { label: "გვერდის სრული ტექსტი", name: "body", widget: "markdown" }] }
      - { file: "src/ka/about.md", label: "ჩვენ შესახებ", name: "about_ka", fields: [{ label: "სათაური", name: "title", widget: "string" }, { label: "ტექსტი", name: "body", widget: "markdown" }] }
      - { file: "src/ka/contact.md", label: "კონტაქტი", name: "contact_ka", fields: [{ label: "სათაური", name: "title", widget: "string" }, { label: "ტექსტი", name: "body", widget: "markdown" }] }

  - name: "pages_en"
    label: "Page Management (English)"
    files:
      - { file: "src/en/index.md", label: "Home Page", name: "index_en", fields: [{ label: "Title", name: "title", widget: "string" }, { label: "Hero Title", name: "hero_title", widget: "string" }, { label: "Hero Subtitle", name: "hero_subtitle", widget: "text" }] }
      - { file: "src/en/services.md", label: "Services Hub (2 Cards)", name: "services_page_en", fields: [{ label: "Title (H1)", name: "title", widget: "string" }, { label: "Subtitle", name: "subtitle", widget: "text" }, { label: "Card 1: Title", name: "card1_title", widget: "string" }, { label: "Card 1: Description", name: "card1_desc", widget: "text" }, { label: "Card 1: List of Points", name: "card1_list", widget: "list", summary: "{{fields.item}}", fields: [{ label: "Point", name: "item", widget: "string" }] }, { label: "Card 2: Title", name: "card2_title", widget: "string" }, { label: "Card 2: Description", name: "card2_desc", widget: "text" }, { label: "Card 2: List of Points", name: "card2_list", widget: "list", summary: "{{fields.item}}", fields: [{ label: "Point", name: "item", widget: "string" }] }] }
      - { file: "src/en/projects.md", label: "Projects Page", name: "projects_page_en", fields: [{ label: "Title (H1)", name: "title", widget: "string" }, { label: "Full Page Content", name: "body", widget: "markdown" }] }
      - { file: "src/en/about.md", label: "About Us", name: "about_en", fields: [{ label: "Title", name: "title", widget: "string" }, { label: "Body", name: "body", widget: "markdown" }] }
      - { file: "src/en/contact.md", label: "Contact", name: "contact_en", fields: [{ label: "Title", name: "title", widget: "string" }, { label: "Body", name: "body", widget: "markdown" }] }
          
  - name: "settings"
    label: "ზოგადი პარამეტრები"
    files:
      - file: "src/_data/settings.json"
        label: "საიტის პარამეტრები"
        name: "settings"
        fields:
          - { label: "ლოგოს ტექსტი", name: "logo_text", widget: "string" }
          - { label: "ტექსტი ფუთერში", name: "footer_text", widget: "string" }