backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow
media_folder: "src/assets/img"
public_folder: "/assets/img"

collections:
  - name: "services"
    label: "სერვისების კატალოგი"
    folder: "src/services"
    create: true
    slug: "{{slug}}"
    identifier_field: "slug"
    sortable_fields: ['sort_order', 'title']
    fields:
      - { label: "ფაილის სახელი (ლათინურად, ტირეებით)", name: "slug", widget: "string", hint: "მაგ: help-desk, it-support. ეს იქნება ფაილის სახელი და ბმული." }
      - { label: "კატეგორიის სათაური", name: "title", widget: "string" }
      - { label: "რიგითობა", name: "sort_order", widget: "number", default: 0 }
      - { label: "იკონი (Lucide)", name: "icon", widget: "string", required: false, hint: "არასავალდებულო. lucide.dev-იდან, მაგ: server" }
      - label: "სერვისების სია (მოკლე აღწერა)"
        name: "service_list"
        widget: "list"
        summary: "{{fields.name}}"
        field: { label: "სერვისის დასახელება", name: "name", widget: "string" }
      - label: "სრული აღწერის პუნქტები"
        name: "detailed_list"
        widget: "list"
        summary: "{{fields.point}}"
        fields:
          - { label: "აღწერის პუნქტი", name: "point", widget: "string" }
      - { label: "Tags", name: "tags", widget: "hidden", default: "services" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "service-detail.njk" }
      - { label: "Permalink", name: "permalink", widget: "hidden", default: "/services/{{slug}}/" }

  - name: "pages"
    label: "მთავარი გვერდები"
    files:
      - { file: "src/index.md", label: "მთავარი გვერდი", name: "index", fields: [{ label: "სათაური", name: "title", widget: "string" }, { label: "Hero-ს სათაური", name: "hero_title", widget: "string" }, { label: "Hero-ს ქვესათაური", name: "hero_subtitle", widget: "text" }] }
      - { file: "src/services.md", label: "სერვისების გვერდი", name: "services_page", fields: [{ label: "სათაური", name: "title", widget: "string" }, { label: "მარცხენა მენიუს სათაური", name: "katalogis_dasaxeleba", widget: "string" }] }
      - { file: "src/about.md", label: "ჩვენ შესახებ", name: "about", fields: [{ label: "სათაური", name: "title", widget: "string" }, { label: "ტექსტი", name: "body", widget: "markdown" }] }
      - { file: "src/contact.md", label: "კონტაქტი", name: "contact", fields: [{ label: "სათაური", name: "title", widget: "string" }, { label: "ტექსტი", name: "body", widget: "markdown" }] }

  - name: "settings"
    label: "ზოგადი პარამეტრები"
    files:
      - { file: "src/_data/settings.json", label: "საიტის პარამეტრები", name: "settings", fields: [{ label: "ლოგოს ტექსტი", name: "logo_text", widget: "string" }, { label: "ტექსტი ფუთერში", name: "footer_text", widget: "string" }] }