backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/img"
public_folder: "/assets/img"

collections:
  - name: "pages"
    label: "მთავარი გვერდები"
    files:
      # ... (pages კოლექცია უცვლელია)
  - name: "services"
    label: "სერვისები"
    folder: "src/services"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "სათაური", name: "title", widget: "string" }
      - { label: "აღწერა", name: "description", widget: "text" }
      # --- მთავარი ცვლილება ---
      - label: "იკონის სახელი (Lucide)"
        name: "icon"
        widget: "string"
        hint: "შედით lucide.dev-ზე, იპოვეთ იკონი და ჩაწერეთ მისი სახელი. მაგ: server, shield, cloud"
      - { label: "იკონის ფერი", name: "icon_color", widget: "select", options: ["lavender", "pink"] }
      - { label: "ანიმაციის დაყოვნება (ms)", name: "aos_delay", widget: "string" }
      - { label: "Tags", name: "tags", widget: "hidden", default: "services" }

  - name: "settings"
    label: "ზოგადი პარამეტრები"
    files:
      # ... (settings კოლექცია უცვლელია)