backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow
media_folder: "src/assets/img"
public_folder: "/assets/img"

collections:
  - name: "services_ka"
    label: "სერვისები (ქართული)"
    folder: "src/services/ka"
    create: true
    slug: "{{slug}}"
    identifier_field: "slug"
    fields:
      - { label: "Tags", name: "tags", widget: "hidden", default: "services" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "service-detail.njk" }
      - { label: "ენა", name: "lang", widget: "hidden", default: "ka" }
      - { label: "Permalink", name: "permalink", widget: "hidden", default: "/services/{{slug}}/" }
      - label: "ფაილის სახელი (ლათინურად, slug)"
        name: "slug"
        widget: "string"
        hint: "მაგ: cloud-hosting. ეს ველი ზუსტად უნდა ემთხვეოდეს ინგლისური ვერსიის slug-ს."
        pattern: ['^[a-z0-9]+(?:-[a-z0-9]+)*$', "გამოიყენეთ მხოლოდ ლათინური ასოები, ციფრები და ტირე"]
      - label: "სერვისის სათაური"
        name: "title"
        widget: "string"
        pattern: ['^[\\u10A0-\\u10FF\\s\\d.,!?-]+$', "გთხოვთ, გამოიყენოთ მხოლოდ ქართული ასოები და სიმბოლოები"] # <<< დაემატა ქართული ენის ვალიდაცია
      - { label: "რიგითობა", name: "sort_order", widget: "number", default: 0 }
      - label: "აირჩიეთ იკონი"
        name: "icon"
        widget: "select"
        required: false
        options:
          - { label: "Users", value: "users" }
          - { label: "Network", value: "network" }
          - { label: "Server", value: "server" }
          - { label: "Cloud", value: "cloud" }
          - { label: "Shield", value: "shield" }
          - { label: "CCTV", value: "cctv" }
          - { label: "Messages", value: "messages" }
          - { label: "Briefcase", value: "briefcase" }
      - label: "ზოგადი მიმოხილვა"
        name: "general_description"
        widget: "markdown"
      - label: "სრული აღწერის პუნქტები"
        name: "detailed_list"
        widget: "list"
        summary: "{{fields.point}}"
        fields:
          - { label: "აღწერის პუნქტი", name: "point", widget: "string" }

  - name: "services_en"
    label: "Services (English)"
    folder: "src/services/en"
    create: true
    slug: "{{slug}}"
    identifier_field: "slug"
    fields:
      - { label: "Tags", name: "tags", widget: "hidden", default: "services" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "service-detail.njk" }
      - { label: "Language", name: "lang", widget: "hidden", default: "en" }
      - { label: "Permalink", name: "permalink", widget: "hidden", default: "/en/services/{{slug}}/" }
      - label: "Filename (slug in latin letters)"
        name: "slug"
        widget: "string"
        hint: "e.g., cloud-hosting. This field must exactly match the slug of the Georgian version."
        pattern: ['^[a-z0-9]+(?:-[a-z0-9]+)*$', "Use only latin letters, numbers, and dashes"]
      - label: "Service Title"
        name: "title"
        widget: "string"
        pattern: ['^[a-zA-Z0-9\\s.,!?-]+$', "Please use only Latin letters and symbols"] # <<< დაემატა ინგლისური ენის ვალიდაცია
      - { label: "Sort Order", name: "sort_order", widget: "number", default: 0 }
      - label: "Icon"
        name: "icon"
        widget: "select"
        required: false
        options:
          - { label: "Users", value: "users" }
          - { label: "Network", value: "network" }
          - { label: "Server", value: "server" }
          - { label: "Cloud", value: "cloud" }
          - { label: "Shield", value: "shield" }
          - { label: "CCTV", value: "cctv" }
          - { label: "Messages", value: "messages" }
          - { label: "Briefcase", value: "briefcase" }
      - label: "General Description"
        name: "general_description"
        widget: "markdown"
      - label: "Detailed List Items"
        name: "detailed_list"
        widget: "list"
        summary: "{{fields.point}}"
        fields:
          - { label: "List Item", name: "point", widget: "string" }
          
  - name: "pages_ka"
    # ... დანარჩენი კოლექციები უცვლელია ...
    label: "მთავარი გვერდები (ქართული)"
    files:
      - { file: "src/ka/index.md", label: "მთავარი გვერდი", name: "index_ka", fields: [{ label: "სათაური", name: "title", widget: "string" }, { label: "Hero-ს სათაური", name: "hero_title", widget: "string" }, { label: "Hero-ს ქვესათაური", name: "hero_subtitle", widget: "text" }] }
      - { file: "src/ka/services.md", label: "სერვისების გვერდი", name: "services_page_ka", fields: [{ label: "სათაური", name: "title", widget: "string" }, { label: "სექციის სათაური", name: "section_title", widget: "string" }, { label: "სექციის ქვესათაური", name: "section_subtitle", widget: "text" }] }
      - { file: "src/ka/about.md", label: "ჩვენ შესახებ", name: "about_ka", fields: [{ label: "სათაური", name: "title", widget: "string" }, { label: "ტექსტი", name: "body", widget: "markdown" }] }
      - { file: "src/ka/contact.md", label: "კონტაქტი", name: "contact_ka", fields: [{ label: "სათაური", name: "title", widget: "string" }, { label: "ტექსტი", name: "body", widget: "markdown" }] }

  - name: "pages_en"
    label: "Main Pages (English)"
    files:
      - { file: "src/en/index.md", label: "Home Page", name: "index_en", fields: [{ label: "Title", name: "title", widget: "string" }, { label: "Hero Title", name: "hero_title", widget: "string" }, { label: "Hero Subtitle", name: "hero_subtitle", widget: "text" }] }
      - { file: "src/en/services.md", label: "Services Page", name: "services_page_en", fields: [{ label: "Title", name: "title", widget: "string" }, { label: "Section Title", name: "section_title", widget: "string" }, { label: "Section Subtitle", name: "section_subtitle", widget: "text" }] }
      - { file: "src/en/about.md", label: "About Us", name: "about_en", fields: [{ label: "Title", name: "title", widget: "string" }, { label: "Body", name: "body", widget: "markdown" }] }
      - { file: "src/en/contact.md", label: "Contact", name: "contact_en", fields: [{ label: "Title", name: "title", widget: "string" }, { label: "Body", name: "body", widget: "markdown" }] }
          
  - name: "settings"
    label: "ზოგადი პარამეტრები"
    files:
      - file: "src/_data/settings.json"
        label: "საიტის პარამეტრები"
        name: "settings"
        fields:
          - { label: "ლოგოს ტექსტი", name: "logo_text", widget: "string" }
          - { label: "ტექსტი ფუთერში", name: "footer_text", widget: "string" }