backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/img"
public_folder: "/assets/img"

collections:
  - name: "categories"
    label: "სერვისების კატალოგი"
    folder: "src/categories"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "ფაილის სახელი (ლათინურად, ტირეებით)", name: "slug", widget: "string", hint: "მაგ: help-desk, it-support. ეს იქნება გვერდის ბმული." }
      - { label: "კატეგორიის სათაური", name: "kategoriis_dasaxeleba", widget: "string" }
      - { label: "რიგითობა", name: "sort_order", widget: "number", hint: "დაბალი რიცხვი ნიშნავს უფრო წინ გამოჩენას" }
      - label: "სერვისების სია (ამ კატეგორიაში)"
        name: "servisebis_sia"
        widget: "list"
        fields: # <<< ეს იყო მთავარი შეცდომა, field-ის ნაცვლად უნდა იყოს fields
          - { label: "სერვისის დასახელება", name: "name", widget: "string" }
      - label: "დეტალური აღწერა (გამოჩნდება 'დეტალურად' გვერდზე)"
        name: "body"
        widget: "markdown"
      - { label: "Tags", name: "tags", widget: "hidden", default: "categories" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "service-detail.njk" }
      - { label: "Permalink", name: "permalink", widget: "hidden", default: "/services/{{slug}}/" }

  - name: "pages"
    label: "მთავარი გვერდები"
    # ... (დანარჩენი კოდი უცვლელია)