backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow
media_folder: "src/assets/img"
public_folder: "/assets/img"

i18n:
  structure: multiple_folders
  locales: [ka, en]
  default_locale: ka

collections:
  - name: "services"
    label: "სერვისების კატალოგი"
    folder: "src/services/{{lng}}"
    create: true
    i18n: true # <-- მხოლოდ ეს არის საჭირო კოლექციის დონეზე
    slug: "{{slug}}"
    identifier_field: "slug"
    sortable_fields: ['sort_order', 'title']
    fields:
      # --- წაიშალა ზედმეტი i18n პარამეტრები ველებიდან ---
      - label: "ფაილის სახელი (ლათინურად, ტირეებით)"
        name: "slug"
        widget: "string"
        hint: "მაგ: help-desk, it-support. ეს იქნება ფაილის სახელი და ბმული."
        pattern: ['^[a-z0-9]+(?:-[a-z0-9]+)*$', "გამოიყენეთ მხოლოდ ლათინური ასოები, ციფრები და ტირე"]
      - { label: "სერვისის სათაური", name: "title", widget: "string" }
      - { label: "რიგითობა", name: "sort_order", widget: "number", default: 0 }
      - label: "აირჩიეთ იკონი"
        name: "icon"
        widget: "select"
        required: false
        options:
          - { label: "Users", value: "users" }
          - { label: "Network", value: "network" }
          - { label: "Server", value: "server" }
          - { label: "Cloud", value: "cloud" }
          - { label: "Shield", value: "shield" }
          - { label: "CCTV", value: "cctv" }
          - { label: "Messages", value: "messages" }
          - { label: "Briefcase", value: "briefcase" }
      - label: "ზოგადი მიმოხილვა (დეტალური გვერდისთვის)"
        name: "general_description"
        widget: "markdown"
      - label: "სრული აღწერის პუნქტები"
        name: "detailed_list"
        widget: "list"
        summary: "{{fields.point}}"
        fields:
          - { label: "აღწერის პუნქტი", name: "point", widget: "string" }
      - { label: "Tags", name: "tags", widget: "hidden", default: "services" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "service-detail.njk" }
      - { label: "Permalink", name: "permalink", widget: "hidden", default: "/services/{{slug}}/" }

  - name: "pages_ka"
    label: "მთავარი გვერდები (ქართული)"
    files:
      - file: "src/ka/index.md"
        label: "მთავარი გვერდი"
        name: "index_ka"
        fields:
          - { label: "სათაური", name: "title", widget: "string" }
          - { label: "Hero-ს სათაური", name: "hero_title", widget: "string" }
          - { label: "Hero-ს ქვესათაური", name: "hero_subtitle", widget: "text" }
      - file: "src/ka/services.md"
        label: "სერვისების გვერდი"
        name: "services_page_ka"
        fields:
          - { label: "სათაური", name: "title", widget: "string" }
          - { label: "სექციის სათაური", name: "section_title", widget: "string" }
          - { label: "სექციის ქვესათაური", name: "section_subtitle", widget: "text" }
      - file: "src/ka/about.md"
        label: "ჩვენ შესახებ"
        name: "about_ka"
        fields:
          - { label: "სათაური", name: "title", widget: "string" }
          - { label: "ტექსტი", name: "body", widget: "markdown" }
      - file: "src/ka/contact.md"
        label: "კონტაქტი"
        name: "contact_ka"
        fields:
          - { label: "სათაური", name: "title", widget: "string" }
          - { label: "ტექსტი", name: "body", widget: "markdown" }

  - name: "pages_en"
    label: "Main Pages (English)"
    files:
      - file: "src/en/index.md"
        label: "Home Page"
        name: "index_en"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Hero Title", name: "hero_title", widget: "string" }
          - { label: "Hero Subtitle", name: "hero_subtitle", widget: "text" }
      - file: "src/en/services.md"
        label: "Services Page"
        name: "services_page_en"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Section Title", name: "section_title", widget: "string" }
          - { label: "Section Subtitle", name: "section_subtitle", widget: "text" }
      - file: "src/en/about.md"
        label: "About Us"
        name: "about_en"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/en/contact.md"
        label: "Contact"
        name: "contact_en"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          
  - name: "settings"
    label: "ზოგადი პარამეტრები"
    files:
      - file: "src/_data/settings.json"
        label: "საიტის პარამეტრები"
        name: "settings"
        fields:
          - { label: "ლოგოს ტექსტი", name: "logo_text", widget: "string" }
          - { label: "ტექსტი ფუთერში", name: "footer_text", widget: "string" }