backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "src/assets/img"
public_folder: "/assets/img"

collections:
  - name: "categories"
    label: "სერვისების კატალოგი"
    folder: "src/categories"
    create: true
    slug: "{{slug}}"
    sortable_fields: ['sort_order', 'kategoriis_dasaxeleba']
    fields:
      - { label: "ფაილის სახელი (ლათინურად, ტირეებით)", name: "slug", widget: "string", hint: "მაგ: help-desk, it-support." }
      - { label: "კატეგორიის სათაური", name: "kategoriis_dasaxeleba", widget: "string" }
      - { label: "რიგითობა", name: "sort_order", widget: "number" }
      - { label: "იკონის სახელი (Lucide)", name: "icon", widget: "string", required: false, hint: "არასავალდებულო. მაგ: server, shield" }
      - label: "სერვისების სია (მთავარი გვერდისთვის)"
        name: "servisebis_sia"
        widget: "list"
        summary: "{{fields.name}}"
        fields: 
          - { label: "სერვისის დასახელება", name: "name", widget: "string" }
          - { label: "იკონის სახელი (Lucide)", name: "icon", widget: "string", required: false }
      - label: "დეტალური აღწერა ('დეტალურად' გვერდზე)"
        name: "body"
        widget: "markdown"
        hint: "სასურველი დიზაინისთვის, გამოიყენეთ ბულეტები. ყოველი პუნქტი დაიწყეთ `-` სიმბოლოთი."

      - { label: "Tags", name: "tags", widget: "hidden", default: "categories" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "service-detail.njk" }
      - { label: "Permalink", name: "permalink", widget: "hidden", default: "/services/{{slug}}/" }

  - name: "pages"
    label: "მთავარი გვერდები"
    # ... (ეს სექცია უცვლელია, დატოვეთ როგორც არის) ...
  - name: "settings"
    label: "ზოგადი პარამეტრები"
    # ... (ეს სექცია უცვლელია, დატოვეთ როგორც არის) ...