backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow
media_folder: "src/assets/img"
public_folder: "/assets/img"

i18n:
  structure: multiple_folders
  locales: [ka, en]
  default_locale: ka

collections:
  - name: "services"
    label: "სერვისების კატალოგი"
    folder: "src/services/{{locale}}" # <<< ვიყენებთ {{locale}} ცვლადს
    create: true
    i18n: true
    slug: "{{slug}}"
    identifier_field: "slug"
    fields:
      - { label: "ფაილის სახელი (ლათინურად, ტირეებით)", name: "slug", widget: "string", i18n: "duplicate" }
      - { label: "სერვისის სათაური", name: "title", widget: "string", i18n: "translate" }
      - { label: "რიგითობა", name: "sort_order", widget: "number", default: 0, i18n: "duplicate" }
      - label: "აირჩიეთ იკონი"
        name: "icon"
        widget: "select"
        required: false
        i18n: "duplicate"
        options:
          - { label: "Users", value: "users" }
          - { label: "Network", value: "network" }
          - { label: "Server", value: "server" }
          - { label: "Cloud", value: "cloud" }
          - { label: "Shield", value: "shield" }
          - { label: "CCTV", value: "cctv" }
          - { label: "Messages", value: "messages" }
          - { label: "Briefcase", value: "briefcase" }
      - { label: "ზოგადი მიმოხილვა", name: "general_description", widget: "markdown", i18n: "translate" }
      - label: "სრული აღწერის პუნქტები"
        name: "detailed_list"
        widget: "list"
        summary: "{{fields.point}}"
        i18n: "translate"
        fields:
          - { label: "აღწერის პუნქტი", name: "point", widget: "string" }
      # --- დამალული ველები, რომლებსაც Eleventy იყენებს ---
      - { label: "Tags", name: "tags", widget: "hidden", default: "services" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "service-detail.njk" }
      - { label: "ენა", name: "lang", widget: "hidden", default: "{{locale}}" }
      - { label: "Permalink", name: "permalink", widget: "hidden" }
      - { label: "Translation Key", name: "translationKey", widget: "hidden", default: "{{slug}}" }

  # --- გვერდების კოლექციები უცვლელია ---
  - name: "pages_ka"
    label: "მთავარი გვერდები (ქართული)"
    files:
      - { file: "src/ka/index.md", label: "მთავარი გვერდი", name: "index_ka", fields: [{ label: "სათაური", name: "title", widget: "string" }, { label: "Hero-ს სათაური", name: "hero_title", widget: "string" }, { label: "Hero-ს ქვესათაური", name: "hero_subtitle", widget: "text" }] }
      - { file: "src/ka/services.md", label: "სერვისების გვერდი", name: "services_page_ka", fields: [{ label: "სათაური", name: "title", widget: "string" }, { label: "სექციის სათაური", name: "section_title", widget: "string" }, { label: "სექციის ქვესათაური", name: "section_subtitle", widget: "text" }] }
      - { file: "src/ka/about.md", label: "ჩვენ შესახებ", name: "about_ka", fields: [{ label: "სათაური", name: "title", widget: "string" }, { label: "ტექსტი", name: "body", widget: "markdown" }] }
      - { file: "src/ka/contact.md", label: "კონტაქტი", name: "contact_ka", fields: [{ label: "სათაური", name: "title", widget: "string" }, { label: "ტექსტი", name: "body", widget: "markdown" }] }

  - name: "pages_en"
    label: "Main Pages (English)"
    files:
      - { file: "src/en/index.md", label: "Home Page", name: "index_en", fields: [{ label: "Title", name: "title", widget: "string" }, { label: "Hero Title", name: "hero_title", widget: "string" }, { label: "Hero Subtitle", name: "hero_subtitle", widget: "text" }] }
      - { file: "src/en/services.md", label: "Services Page", name: "services_page_en", fields: [{ label: "Title", name: "title", widget: "string" }, { label: "Section Title", name: "section_title", widget: "string" }, { label: "Section Subtitle", name: "section_subtitle", widget: "text" }] }
      - { file: "src/en/about.md", label: "About Us", name: "about_en", fields: [{ label: "Title", name: "title", widget: "string" }, { label: "Body", name: "body", widget: "markdown" }] }
      - { file: "src/en/contact.md", label: "Contact", name: "contact_en", fields: [{ label: "Title", name: "title", widget: "string" }, { label: "Body", name: "body", widget: "markdown" }] }
          
  - name: "settings"
    label: "ზოგადი პარამეტრები"
    files:
      - file: "src/_data/settings.json"
        label: "საიტის პარამეტრები"
        name: "settings"
        fields:
          - { label: "ლოგოს ტექსტი", name: "logo_text", widget: "string" }
          - { label: "ტექსტი ფუთერში", name: "footer_text", widget: "string" }