backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/img"
public_folder: "/assets/img"

collections:
  - name: "pages"
    label: "მთავარი გვერდები"
    files:
      - file: "src/index.md"
        label: "მთავარი გვერდი"
        name: "index"
        fields:
          - { label: "გვერდის სათაური (ბრაუზერისთვის)", name: "title", widget: "string" }
          - { label: "მთავარი დიდი სათაური", name: "hero_title", widget: "string" }
          - { label: "Hero-ს ქვესათაური", name: "hero_subtitle", widget: "text" }
          - { label: "სერვისების სექციის სათაური", name: "services_title", widget: "string" }
      - file: "src/about.md"
        label: "ჩვენ შესახებ"
        name: "about"
        fields:
          - { label: "სათაური", name: "title", widget: "string" }
          - { label: "გვერდის ტექსტი", name: "body", widget: "markdown" }
      - file: "src/contact.md"
        label: "კონტაქტი"
        name: "contact"
        fields:
          - { label: "სათაური", name: "title", widget: "string" }
          - { label: "გვერდის ტექსტი", name: "body", widget: "markdown" }

  - name: "services"
    label: "სერვისები"
    folder: "src/services"
    create: true
    # --- მთავარი ცვლილება: ფაილის სახელს ვიღებთ ახალი "slug" ველიდან ---
    slug: "{{fields.slug}}" 
    fields:
      # --- დაემატა ახალი ველი ---
      - label: "ფაილის სახელი (ლათინურად)"
        name: "slug"
        widget: "string"
        hint: "გამოიყენეთ მხოლოდ ლათინური ასოები, ციფრები და ტირე (-). მაგ: kiber-usafrtkhoeba"
      - { label: "სათაური", name: "title", widget: "string" }
      - { label: "აღწერა", name: "description", widget: "text" }
      - { label: "იკონის ფერი", name: "icon_color", widget: "select", options: ["lavender", "pink"] }
      - { label: "იკონი", name: "icon", widget: "select", options: ["mobile", "security", "cloud", "consulting"] }
      - { label: "ანიმაციის დაყოვნება (ms)", name: "aos_delay", widget: "string" }

  - name: "settings"
    label: "ზოგადი პარამეტრები"
    files:
      - file: "src/_data/settings.json"
        label: "საიტის პარამეტრები"
        name: "settings"
        fields:
          - { label: "ლოგოს ტექსტი", name: "logo_text", widget: "string" }
          - { label: "ტექსტი ფუთერში", name: "footer_text", widget: "string" }